spring:
  config:
    import: env-dev.properties
  datasource:
    url: jdbc:mariadb://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false